workflows:
  android-workflow:
    name: Android Build
    environment:
      groups: []
      vars:
        ANDROID_COMPILE_SDK: "33"
        ANDROID_MIN_SDK: "21"
        ANDROID_TARGET_SDK: "33"
    scripts:
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "flutter.compileSdkVersion=$ANDROID_COMPILE_SDK" > "$CM_BUILD_DIR/android/gradle.properties"
          echo "flutter.minSdkVersion=$ANDROID_MIN_SDK" >> "$CM_BUILD_DIR/android/gradle.properties"
          echo "flutter.targetSdkVersion=$ANDROID_TARGET_SDK" >> "$CM_BUILD_DIR/android/gradle.properties"
      - name: Build application
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
